<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TalentSeeder extends Seeder
{
    public function run(): void
    {
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');
        DB::table('talent')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');

        DB::table('talent')->insert([
            ['name' => 'Logical reasoning'],
            ['name' => 'Problem solving'],
            ['name' => 'Critical thinking'],
            ['name' => 'Memory (strong recall ability)'],
            ['name' => 'Analytical thinking'],
            ['name' => 'Mathematical ability'],
            ['name' => 'Abstract thinking'],
            ['name' => 'Fast learning ability'],
            ['name' => 'Strategic thinking'],
            ['name' => 'Pattern recognition'],
            ['name' => 'Research ability'],
            ['name' => 'Software development'],
            ['name' => 'Cybersecurity skills'],
            ['name' => 'Data analysis'],
            ['name' => 'Artificial intelligence / machine learning'],
            ['name' => 'Networking / IT infrastructure'],
            ['name' => 'Hardware engineering'],
            ['name' => 'Cloud computing'],
            ['name' => 'System design'],
            ['name' => 'Robotics'],
            ['name' => 'Electronics repair'],
            ['name' => 'Drawing / painting'],
            ['name' => 'Graphic design'],
            ['name' => 'Animation'],
            ['name' => 'Music composition'],
            ['name' => 'Singing'],
            ['name' => 'Playing instruments'],
            ['name' => 'Photography'],
            ['name' => 'Videography'],
            ['name' => 'Creative writing'],
            ['name' => 'Storytelling'],
            ['name' => 'Fashion design'],
            ['name' => 'Interior design'],
            ['name' => 'Public speaking'],
            ['name' => 'Writing clearly'],
            ['name' => 'Storytelling'],
            ['name' => 'Teaching ability'],
            ['name' => 'Persuasion'],
            ['name' => 'Negotiation'],
            ['name' => 'Foreign languages'],
            ['name' => 'Active listening'],
            ['name' => 'Presentation skills'],
            ['name' => 'Leadership'],
            ['name' => 'Teamwork'],
            ['name' => 'Emotional intelligence'],
            ['name' => 'Conflict resolution'],
            ['name' => 'Networking'],
            ['name' => 'Empathy'],
            ['name' => 'Relationship building'],
            ['name' => 'Mentoring'],
            ['name' => 'Coaching'],
            ['name' => 'Entrepreneurship'],
            ['name' => 'Financial management'],
            ['name' => 'Marketing'],
            ['name' => 'Sales skills'],
            ['name' => 'Risk management'],
            ['name' => 'Decision making'],
            ['name' => 'Innovation'],
            ['name' => 'Product management'],
            ['name' => 'Business strategy'],
            ['name' => 'Carpentry'],
            ['name' => 'Plumbing'],
            ['name' => 'Electrical work'],
            ['name' => 'Mechanical repair'],
            ['name' => 'Construction'],
            ['name' => 'Welding'],
            ['name' => 'Cooking'],
            ['name' => 'Baking'],
            ['name' => 'Sewing'],
            ['name' => 'Gardening'],
            ['name' => 'Running speed'],
            ['name' => 'Strength / bodybuilding'],
            ['name' => 'Coordination'],
            ['name' => 'Agility'],
            ['name' => 'Balance'],
            ['name' => 'Endurance'],
            ['name' => 'Martial arts'],
            ['name' => 'Football / basketball / sports skills'],
            ['name' => 'Dancing'],
            ['name' => 'Swimming'],
            ['name' => 'Emotional control'],
            ['name' => 'Stress management'],
            ['name' => 'Patience'],
            ['name' => 'Discipline'],
            ['name' => 'Focus / concentration'],
            ['name' => 'Motivation'],
            ['name' => 'Resilience'],
            ['name' => 'Self-awareness'],
            ['name' => 'Mindfulness'],
            ['name' => 'Scientific reasoning'],
            ['name' => 'Experiment design'],
            ['name' => 'Hypothesis formulation'],
            ['name' => 'Data interpretation'],
            ['name' => 'Lab skills'],
            ['name' => 'Innovation in science'],
            ['name' => 'Engineering design thinking'],
            ['name' => 'Farming / agriculture'],
            ['name' => 'Animal handling'],
            ['name' => 'Environmental awareness'],
            ['name' => 'Weather interpretation'],
            ['name' => 'Ecology understanding'],
            ['name' => 'Wildlife tracking'],
            ['name' => 'Conservation skills'],
            ['name' => 'Acting'],
            ['name' => 'Comedy'],
            ['name' => 'Stand-up performance'],
            ['name' => 'Stage performance'],
            ['name' => 'Dancing'],
            ['name' => 'Voice acting'],
            ['name' => 'Entertainment hosting'],
            ['name' => 'Planning'],
            ['name' => 'Organizing teams'],
            ['name' => 'Time management'],
            ['name' => 'Delegation'],
            ['name' => 'Vision setting'],
            ['name' => 'Crisis management'],
            ['name' => 'Execution discipline'],
            ['name' => 'Exceptional intuition'],
            ['name' => 'High sensory perception (hearing, vision, smell)'],
            ['name' => 'Photographic memory (rare)'],
            ['name' => 'Synesthesia (cross-sensory perception)'],
            ['name' => 'Extreme creativity bursts'],
            ['name' => 'Exceptional spatial intelligence'],
        ]);
    }
}
